name: Build Docker Image
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'cargo'
      - 'scripts/docker'
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-21.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          # push: true
          context: .
          tags: imperocom/cross:latest
          platforms: linux/amd64,linux/arm64
