name: Build Tools
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed
  push:
    paths:
      - scripts/docker/build.sh
      - scripts/docker/export.sh
env:
  CARGO_INCREMENTAL: 0
jobs:
  build-x86_64:
    name: Build Tools (x86_64)
    runs-on: ubuntu-20.04
    container: imperocom/cross-compiler
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binaries
        run: ./scripts/docker/build_export.sh x86_64

      - name: Check binaries
        run: ls -lh /tools/x86_64

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: x86_64
          path: /tools/x86_64
  build-aarch64:
    name: Build Tools (aarch64)
    runs-on: ubuntu-20.04
    container: imperocom/cross-compiler
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binaries
        run: ./scripts/docker/build_export.sh aarch64

      - name: Check binaries
        run: ls -lh /tools/aarch64

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: aarch64
          path: /tools/aarch64
  create-release:
    name: Create Release
    runs-on: ubuntu-20.04
    needs: [build-x86_64, build-aarch64]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2

      - name: Check downloaded binaries
        run: ls -lh

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            x86_64
            aarch64
          name: ${{ github.sha }}
