name: Build tools
on:
  workflow_dispatch:
  push:
env:
  CARGO_INCREMENTAL: 0
  BIN_VERSION: "0.15.2"
  BIN_NAME: "cargo-audit"
  BIN_TARGET: "aarch64-unknown-linux-musl"
  BIN_FEATURES: "vendored-openssl"
jobs:
  build-cargo-audit:
    name: Build cargo-audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.56
            override: true
            target: ${{ env.BIN_TARGET }}

      - name: Fetch cross
        run: ./tools/fetch-cross.sh

      - name: Build binary
        run: ./cross install $BIN_NAME --version $BIN_VERSION --target $BIN_TARGET --features $BIN_FEATURES

      - name: Check binary
        run: ~/.cargo/bin/$BIN_NAME --help

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BIN_TARGET }}
          path: ~/.cargo/bin/${{ env.BIN_NAME }}
