name: Build Tools
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed
  push:
    paths:
      # Do not trigger this workflow if
      # the Docker image workflow was triggered
      - '!Dockerfile'
      - '!.cargo'
      - '!scripts/install.sh'
      - '!.github/workflows/build-image.yml'

      - '.github/workflows/build-tools.yml'
env:
  CARGO_INCREMENTAL: 0
jobs:
  build-x86_64:
    name: Build Tools (x86_64)
    runs-on: ubuntu-20.04
    container: imperocom/cross-compiler
    steps:
      - name: Build binaries
        run: /scripts/build.sh x86_64-unknown-linux-gnu

      - name: Export binaries
        run: /scripts/export.sh /export

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: x86_64
          path: /export
  build-aarch64:
    name: Build Tools (aarch64)
    runs-on: ubuntu-20.04
    container: imperocom/cross-compiler
    steps:
      - name: Build binaries
        run: /scripts/build.sh aarch64-unknown-linux-gnu

      - name: Export binaries
        run: /scripts/export.sh /export

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: aarch64
          path: /export
  create-release:
    name: Create Release
    runs-on: ubuntu-20.04
    needs: [build-x86_64, build-aarch64]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2

      - name: Check downloaded binaries (x86_64)
        run: ls -lh x86_64/

      - name: Check downloaded binaries (aarch64)
        run: ls -lh aarch64/

      - name: Zip binaries
        run: zip -r x86_64.zip x86_64 && zip -r aarch64.zip aarch64

      - name: Extract tag name
        run: echo GITHUB_TAG="${GITHUB_REF##refs/tags/}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            x86_64.zip
            aarch64.zip
          name: ${{ env.GITHUB_TAG }}
