name: Build Docker Image
on:
  workflow_dispatch:
  push:
    paths:
      # Update build-tools.yml accordingly
      # if you change any of the paths here
      # including the last
      - 'Dockerfile'
      - '.cargo'
      - 'scripts/install.sh' 
      - '.github/workflows/build-image.yml'
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          tags: imperocom/cross-compiler:next

      - name: Build & push image (master)
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          push: true
          context: .
          tags: imperocom/cross-compiler:master

      - name: Build & push image (latest)
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: .
          tags: imperocom/cross-compiler:latest
