name: Build tools
on:
  workflow_dispatch:
  push:
env:
  CARGO_INCREMENTAL: 0
  BIN_VERSION: "0.15.2"
  BIN_NAME: "cargo-audit"
  BIN_TARGET: "aarch64-unknown-linux-gnu"
  BIN_FEATURES: "vendored-openssl"
jobs:
  build-cargo-audit:
    name: Build cargo-audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.56
            override: true
            target: ${{ env.BIN_TARGET }}

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: install
          args: ${{ env.BIN_NAME }} --version ${{ env.BIN_VERSION }} --target ${{ env.BIN_TARGET }} --features ${{ env.BIN_FEATURES }}

      - name: Check binary
        run: ~/.cargo/bin/$BIN_NAME --help

      - name: Add full binary name to environment
        run: echo BIN_FULL_NAME=$BIN_NAME-$BIN_VERSION-$BIN_TARGET >> $GITHUB_ENV

      - name: Rename binary
        run: mv ~/.cargo/bin/$BIN_NAME $BIN_FULL_NAME

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BIN_FULL_NAME }}
          path: ${{ env.BIN_FULL_NAME }}
