name: Cleanup
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  delete-image-artifact:
    name: Delete unused artifact
    runs-on: ubuntu-20.04
    steps:
      - name: Delete image artifact
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            console.log(github);
            console.log(context);
