name: Create Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: Download binaries (x86_64)
        uses: impero-com/action-download-artifact@v2
        with:
          workflow: build-tools.yml
          workflow_conclusion: success
          branch: master
          name: x86_64
          commit: ${{ github.sha }}
          path: ${{ github.workspace }}

      - name: Download binaries (aarch64)
        uses: impero-com/action-download-artifact@v2
        with:
          workflow: build-tools.yml
          workflow_conclusion: success
          branch: master
          name: aarch64
          commit: ${{ github.sha }}
          path: ${{ github.workspace }}

      - name: Check downloaded binaries (x86_64)
        run: ls -lh x86_64/

      - name: Check downloaded binaries (aarch64)
        run: ls -lh aarch64/

      - name: Get tag name
        run: echo GITHUB_TAG="${GITHUB_REF##refs/tags/}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            x86_64
            aarch64
          name: ${{ env.GITHUB_TAG }}
